# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  docker:
    - image: circleci/node:12.16

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - persist_to_workspace:
          root: ~/
          paths:
            - ./*

  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npm run test

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run release

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Deploy Master to Firebase
          command: npm run deploy

workflows:
  version: 2

  build-test-release:
    jobs:
      - build
      - test
      - release:
          requires:
            - build
            - test
          filters:
            branches:
              only: master

  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
